name: Deploy test function

on:
  push: 
    branches: [ main ]
  
  # run workflow   
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install npm packages
        run: | 
          cd functions
          npm ci
          npm install firebase-tools
      - name: Deploy to Firebase
        run: pwd && npm run deploy:dev
        env:
          FIREBASE_TOKEN: "1//0g2eerzI4IFMqCgYIARAAGBASNwF-L9IrrSui-UCkwvdPb5bsvyfzs0eVUij4bsI40BJaeY2Xl2rj8sL0WcpqdYeNbQg8OB8RlUg"