name: Deploy test function

on:
  push: 
    branches: [ main ]
  
  # run workflow   
  workflow_dispatch:
    
jobs:
  build_and_deploy_functions_uat:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install npm packages
        run: | 
          cd functions
          npm ci
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions
        env:
          FIREBASE_TOKEN: "1//0g2eerzI4IFMqCgYIARAAGBASNwF-L9IrrSui-UCkwvdPb5bsvyfzs0eVUij4bsI40BJaeY2Xl2rj8sL0WcpqdYeNbQg8OB8RlUg"